"""This type stub file was generated by cyright."""

import cython
from enum import Enum
from typing import Any, Optional

class TimeUnits(Enum):
    ms = ...
    seconds = ...
    minutes = ...
    hours = ...
    days = ...

class ProgressBar:
    """A simple progress bar object."""
    def __init__(
        self, num_jobs: int, print_on_exit: bool = ..., print_interval: float = ...
    ) -> None: ...
    def increment(self, increment: int = ...) -> None:
        """Increment the current value of the progress bar by the given amount."""

    @property
    def value(self) -> int:
        """Value getter property. Returns the current value."""
    @value.setter
    def value(self, new_value: int) -> None:
        """Value setter."""

    def update(self) -> None:
        """Force an update of the progress bar."""

    def __repr__(self) -> str: ...
    def complete(self) -> None:
        """Manually set the bar to complete."""

    def __enter__(self) -> ProgressBar:
        """Context manager method to start the execution timer."""

    def __exit__(self, exc_type, exc_value, traceback) -> bool | None: ...
    def __str__(self) -> str:
        """Convert result from seconds to hours, minutes, seconds, and/or milliseconds."""
